### ISSUE TITLE
Skipping cacheResponse breaks custom methods and computed properties

### ISSUE THREAD

**Issue by kevinob11** [js-data/js-data-angular#332] opened 2015-04-25 02:37 UTC
I want to skip caching the response from all of my `findAll` calls, but when I do this my objects never receive their custom methods and computed properties. I'm skipping the cache because our app gets a lot of updates from many different users and I don't want to show any stale data. I can't set up sockets at this point so I want to just always retrieve from the server. So on some level I just want to use js-data-angular for it's automatic REST request builder but be able to turn on the data store level later. Any way to completely disable the caching features without losing custom methods and computed props?

**Comment by jmdobry** [comment] 2015-04-26 01:12
If you set `cacheReponse: false` and you're using the latest js-data:

Custom methods should still work as long as you did not set `useClass` to `false`.

Computed properties should also be computed once for the data pulled from the server, but will not be recomputed when the data changes because the data was not injected into the store. This is the expected behavior, and I updated the documentation to say so.

-----

Closing because I’m not sure this is an issue, if you are convinced that this is really a bug, please feel free to re-open the issue and add more information:
- good - Your versions of js-data, js-data-angular, etc, relevant console logs/error, code examples that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

Otherwise support is done via the [Gitter Channel](https://gitter.im/js-data/js-data) or the [mailing list](https://groups.io/org/groupsio/jsdata).

**Closed by jmdobry** 2015-04-26 01:12 UTC
