### ISSUE TITLE
bindOne on a model with a many-to-many relationship is causing "10 $digest() iterations reached" error

### ISSUE THREAD

**Issue by stringbeans** [js-data/js-data-angular#333] opened 2015-05-21 21:08 UTC
I have 3 models...
user
agent (join table between user and agency)
agency

to represent the many-to-many relationship between user and agency, i have a computed property on the user model that well return an array of agencies based on the hasMany relationship that the user has with the agent.

```
  agencies: ['agents', function (agents) {
        var params = {
          where: {
            agencyId: {
              in: _.pluck(agents, 'agencyId')
            }
          }
        }

        return DS.filter('agency', params)
      }]
```

I use a bindOne to listen to when a particular user is loaded in, however I'm noticing that it is triggered almost infinitely...
```
DS.bindOne('user', 147, scope, 'whatever', function(err, user){
  console.log(user) // this is printed out infinitely
})
```

However! If instead I use a bindAll and filter where the userId is equal to some value, it is only called once (as expected).

Any ideas?

**Comment by jmdobry** [comment] 2015-05-21 21:36
Hmm, I tried to duplicate it with [this plunker](http://plnkr.co/edit/wveT2J?p=preview), but I couldn't. Could you take a look at it?

**Comment by stringbeans** [comment] 2015-05-22 01:57
Thanks for your quick response @jmdobry ! I haven't found time yet to reproduce this in a plunker but I also want to add that I discovered this in Firefox. In Chrome this would only occur occassionally :confused:

**Comment by jmdobry** [comment] 2015-07-01 14:57
Can you try again with js-data 2.0.0-rc.1 and js-data-angular 3.0.0-rc.1?

**Comment by jmdobry** [comment] 2015-09-20 21:58
Here is the plunker again: http://plnkr.co/edit/wveT2J?p=preview, this time with the latest versions of of js-data and js-data-angular. I can't reproduce the error.

@stringbeans Closing this issue, but if you can show me a plunker that reproduces the issue, feel free to re-open.

**Closed by jmdobry** 2015-09-20 21:58 UTC
Labels: bug
